name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Copy JAR to Remote Server
      run: |
        scp /Users/serhiimischenko/IdeaProjects/TelegramCurrancyBot/target/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar ubuntu@3.79.25.199:/home/ubuntu/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar

    - name: Run JAR on Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa $REMOTE_USER@$REMOTE_HOST "java -jar /path/to/remote/folder/your_bot.jar"
