name: maven

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Add SSH known host
      run: |
        mkdir -p $HOME/.ssh
        ssh-keyscan -H ec2-3-79-25-199.eu-central-1.compute.amazonaws.com >> $HOME/.ssh/known_hosts

    - name: Set up environment
      run: echo "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY" >> $GITHUB_ENV
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Stop the Running Project
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        if pgrep -f "telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar" > /dev/null; then
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-79-25-199.eu-central-1.compute.amazonaws.com "pkill -f telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar"
        fi

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Deploy to AWS
      run: |
        scp -i ssh_key.pem /Users/serhiimischenko/IdeaProjects/TelegramCurrancyBot/target/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar ubuntu@3.79.25.199:/home/ubuntu/
        ssh -i ssh_key.pem ubuntu@ec2-3-79-25-199.eu-central-1.compute.amazonaws.com
