name: maven

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Stop the Running Project
      run: |
        ssh -i /Users/serhiimischenko/ ssh -i /Users/serhiimischenko/.ssh/bot.pem ubuntu@ec2-3-79-25-199.eu-central-1.compute.amazonaws.com "pkill -f telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar"


    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to AWS
      run: |
        scp -i $AWS_SSH_KEY -r ./target/myproject.jar $AWS_USER@$AWS_SERVER_IP:/path/to/remote/directory
        ssh -i "bot.pem" ubuntu@ec2-3-79-25-199.eu-central-1.compute.amazonaws.com

