on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Create home directory and known_hosts
      run: |
        mkdir -p $HOME/.ssh
        touch $HOME/.ssh/known_hosts
        ssh-keyscan -t ecdsa,rsa,ed25519 3.66.171.180 >> $HOME/.ssh/known_hosts
        
    - name: Build with Maven
      run: | 
        mvn clean install -DskipTests
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key

    - name: Deploy to AWS
      run: |
        scp -i ~/.ssh/private.key target/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar ubuntu@3.66.171.180:/home/ubuntu/
