on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Create home directory and known_hosts
      run: |
        mkdir -p $HOME/.ssh
        touch $HOME/.ssh/known_hosts
        ssh-keyscan -t ecdsa,rsa,ed25519 3.66.171.180 >> $HOME/.ssh/known_hosts
        
    - name: Build with Maven
      run: | 
        mvn clean install -DskipTests
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key

    - name: Transfer config.properties
      run: |
        echo "${{ secrets.CONFIG_PROPERTIES }}" > config.properties
        scp -i ~/.ssh/private.key config.properties ubuntu@3.66.171.180:/home/ubuntu/  

    - name: Stop the Old Application
      run: |
        if pgrep -f telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar > /dev/null; then
          ssh -i ~/.ssh/private.key ubuntu@3.66.171.180 "pkill -f telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar"
        else
          echo "Process not found, no need to stop."
        fi

    - name: Remove Old JAR
      run: |
        ssh -i ~/.ssh/private.key ubuntu@3.66.171.180 "rm -f /home/ubuntu/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar"

    - name: Deploy the New JAR
      run: |
        scp -i ~/.ssh/private.key target/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar ubuntu@3.66.171.180:/home/ubuntu/
        
    - name: Start the New Application in Background
      run: |
        ssh -i ~/.ssh/private.key ubuntu@3.66.171.180 "nohup java -jar /home/ubuntu/telegram-bot-get-currency-rate-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"
